// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-west-2",
    "aws_cognito_identity_pool_id": "us-west-2:0c5581c7-3999-44af-9dec-3ffe9c34c757",
    "aws_cognito_region": "us-west-2",
    "aws_user_pools_id": "us-west-2_NOUaoo6CH",
    "aws_user_pools_web_client_id": "18bgijnmukkmfinbtqcr9qbsd6",
    "oauth": {},
    "aws_appsync_graphqlEndpoint": "https://iourtajgivdy7mobj7mw2l7z2e.appsync-api.us-west-2.amazonaws.com/graphql",
    "aws_appsync_region": "us-west-2",
    "aws_appsync_authenticationType": "AMAZON_COGNITO_USER_POOLS"
};


export default awsmobile;
